In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 


Bad key "text.kerning_factor" on line 4 in
/home/gufopc/anaconda3/envs/fastai-cpu/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution


In [2]:
data = ("Downloads/Data/glass.csv")
glassdata = pd.read_csv(data)

In [3]:
print(np.unique(glassdata['Type']))

[1 2 3 5 6 7]


In [4]:
glassdata

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [5]:
glassdata.describe().T

count       mean       std       min        25%       50%        75%  \
RI    214.0   1.518365  0.003037   1.51115   1.516523   1.51768   1.519157   
Na    214.0  13.407850  0.816604  10.73000  12.907500  13.30000  13.825000   
Mg    214.0   2.684533  1.442408   0.00000   2.115000   3.48000   3.600000   
Al    214.0   1.444907  0.499270   0.29000   1.190000   1.36000   1.630000   
Si    214.0  72.650935  0.774546  69.81000  72.280000  72.79000  73.087500   
K     214.0   0.497056  0.652192   0.00000   0.122500   0.55500   0.610000   
Ca    214.0   8.956963  1.423153   5.43000   8.240000   8.60000   9.172500   
Ba    214.0   0.175047  0.497219   0.00000   0.000000   0.00000   0.000000   
Fe    214.0   0.057009  0.097439   0.00000   0.000000   0.00000   0.100000   
Type  214.0   2.780374  2.103739   1.00000   1.000000   2.00000   3.000000   

           max  
RI     1.53393  
Na    17.38000  
Mg     4.49000  
Al     3.50000  
Si    75.41000  
K      6.21000  
Ca    16.19000  
Ba     3.15000  
Fe     0.51000  
Type   7.00000

above we can see that 25-75 % of data is 0

In [6]:
print((glassdata["Ba"]==0).sum()/len(glassdata))
print((glassdata["Fe"]==0).sum()/len(glassdata))

0.822429906542056
0.6728971962616822


82% and 67% of Ba and Fe data is 0

In [7]:
print(glassdata)

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]


In [8]:
glassdata.drop("Ba",axis = 1,inplace=True)
glassdata.drop("Fe",axis = 1,inplace=True)

In [9]:
print(glassdata)

          RI     Na    Mg    Al     Si     K    Ca  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07     1
..       ...    ...   ...   ...    ...   ...   ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62     7

[214 rows x 8 columns]


In [10]:
from sklearn.model_selection import train_test_split

X = glassdata.iloc[:,:-1]
Y = glassdata.iloc[:,-1]
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.4)

In [13]:
from sklearn.svm import SVC

svm = SVC(kernel = "linear",C=0.5)
svm.fit(X_train,y_train.values.ravel())

SVC(C=0.5, kernel='linear')

In [14]:
y_predct = svm.predict(X_test)
print(y_predct)
print(y_test)

[1 1 1 1 1 1 1 1 1 7 1 5 1 1 1 1 2 7 1 2 5 5 1 1 7 7 1 2 7 2 1 7 7 2 1 1 2
 1 1 2 1 5 1 1 2 1 2 2 7 2 1 1 5 2 1 1 1 5 5 2 1 7 7 2 5 2 2 1 1 7 7 1 2 1
 7 6 7 1 1 1 2 1 1 5 2 1]
102    2
50     1
64     1
147    3
38     1
      ..
78     2
116    2
172    5
129    2
0      1
Name: Type, Length: 86, dtype: int64


In [15]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


print(accuracy_score(y_test,y_predct))

0.6046511627906976


In [19]:
print(confusion_matrix(y_test,y_predct))

[[19  4  0  0  0  0]
 [19 14  0  1  0  0]
 [ 5  1  0  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  1  1  0]
 [ 0  0  0  3  0 14]]


# using Knn

In [21]:
from sklearn import neighbors

clf = neighbors.KNeighborsClassifier()
clf.fit(X_train,y_train)
print(accuracy_score(y_test,y_predct))

print(confusion_matrix(y_test,y_predct))


0.6046511627906976
[[19  4  0  0  0  0]
 [19 14  0  1  0  0]
 [ 5  1  0  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  1  1  0]
 [ 0  0  0  3  0 14]]


In [22]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [23]:
clf = DecisionTreeClassifier(random_state=0)

ValueError: Found input variables with inconsistent numbers of samples: [128, 86]